### PR TITLE
Adding refresh to GH APP token

### PR DESCRIPTION
**Pull request by djredman99**
@NickLiffen 

Would this be all that is required to keep the token refreshed each time auth is used?

It looks like that for each repo it loops through, it acquires token.  With the default refresh set to 'false' for [octokit](https://github.com/octokit/auth-app.js/tree/9537cb4ef84870aac702e6ed675a2afce9ebd9be#installation-authentication), it is getting the original token each time.  With this update, I assume it will get a new token each time.

### CODE REVIEW

**Comment by djredman99** [comment]
In regards to #77

**Comment by NickLiffen** [comment]
@djredman99 I think this will do it, but I don't have a test to run this one where I can see if it does run on an org longer then 60 minutes 😢 Let's try this, if this doesn't work I have another idea on how to get this working. My only thought here is this function is only called once, it isn't called multiple times, so how does it know when to invoke the refresh? 🤔

**Comment by djredman99** [comment]
The way I read the code, I thought that this would get called for each repo it loops through as seen here https://github.com/NickLiffen/ghas-enablement/blob/dc3af5e854f47e2a37d05663f28737303b010b84/src/utils/worker.ts#L48

**Comment by NickLiffen** [comment]
Going to close this PR in replacement of #79

**Comment by NickLiffen** [comment]
I would like to note here @djredman99 spearheaded this fix and was the one who is driving this to completion 🥳

**Pull request closed without merging**
